# Generated by Django 2.0.6 on 2018-07-08 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1023)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('arrival_time', models.DateTimeField(auto_now=True)),
                ('mug_shot', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FriendAccomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomplishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.Accomplishment')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.Friend')),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='has_accomplished',
            field=models.ManyToManyField(auto_created=True, blank=True, through='friends.FriendAccomplishment', to='friends.Accomplishment'),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='accomplished_by',
            field=models.ManyToManyField(auto_created=True, blank=True, through='friends.FriendAccomplishment', to='friends.Friend'),
        ),
    ]
